#include "user_data.h"
#include <cassert>
#include <filesystem>
int main(){
 const auto root=std::filesystem::temp_directory_path()/"vant-user-data-test";std::filesystem::remove_all(root);
 {vantage::UserDataStore data(root/"data.sqlite3");data.add_bookmark({"https://example.com","Example"});data.add_bookmark({"https://example.com","Renamed"});assert(data.bookmarks().size()==1&&data.bookmarks()[0].title=="Renamed");assert(data.is_bookmarked("https://example.com"));data.add_history("https://example.com","Example",10);data.add_history("https://second.example","Second",20);assert(data.history().size()==2&&data.history()[0].title=="Second");data.clear_history();assert(data.history().empty());const auto download=data.add_download("https://example.com/file","/tmp/file","downloading",30);data.update_download(download,"complete");assert(data.downloads().size()==1&&data.downloads()[0].status=="complete");data.set_permission("https://example.com","camera",vantage::Permission::deny);assert(data.permission("https://example.com","camera")==vantage::Permission::deny);assert(data.permission("https://example.com","geolocation")==vantage::Permission::ask);data.remove_bookmark("https://example.com");assert(data.bookmarks().empty());}
 assert(vantage::safe_download_path(root,"../../passwd")==root/"passwd");assert(vantage::safe_download_path(root,".profile")==root/"download.profile");assert(vantage::safe_download_path(root,std::string("bad\0name",8))==root/"badname");
 const auto private_path=root/"private.sqlite3";{vantage::UserDataStore data(private_path,true);data.add_bookmark({"https://private.invalid","Private"});assert(data.bookmarks().size()==1);data.add_history("https://private.invalid","Private",1);assert(data.history().empty());assert(data.add_download("https://private.invalid/file","/tmp/file","complete",1)==0);assert(data.downloads().empty());}assert(!std::filesystem::exists(private_path));std::filesystem::remove_all(root);
}
