#include "user_data.h"
#include <cassert>
#include <filesystem>
#include <fstream>
int main(){
 const auto root=std::filesystem::temp_directory_path()/"vant-user-data-test";std::filesystem::remove_all(root);
 {vantage::UserDataStore data(root/"data.sqlite3");data.add_bookmark({"https://example.com","Example"});data.add_bookmark({"https://example.com","Renamed"});assert(data.bookmarks().size()==1&&data.bookmarks()[0].title=="Renamed");assert(data.is_bookmarked("https://example.com"));data.update_bookmark("https://example.com",{"https://example.org","Edited"});assert(data.is_bookmarked("https://example.org"));data.add_history("https://example.com","Example",10);data.add_history("https://second.example","Second",20);const auto history=data.history();assert(history.size()==2&&history[0].title=="Second");data.remove_history({history[0].id});assert(data.history().size()==1);data.clear_history();assert(data.history().empty());const auto download=data.add_download("https://example.com/file","/tmp/file","downloading",30);data.update_download_progress(download,256,7234);auto downloads=data.downloads();assert(downloads.size()==1&&downloads[0].received==256&&downloads[0].total==7234);data.update_download(download,"complete");assert(data.downloads()[0].status=="complete");data.remove_download(download);assert(data.downloads().empty());data.set_permission("https://example.com","camera",vantage::Permission::deny);assert(data.permission("https://example.com","camera")==vantage::Permission::deny);assert(data.permission("https://example.com","geolocation")==vantage::Permission::ask);data.remove_bookmark("https://example.org");assert(data.bookmarks().empty());}
 {vantage::UserDataStore data(root/"favicon.sqlite3");data.set_favicon("https://legacy.example","data:image/x-icon;base64,iVBORw0KGgo=");assert(data.favicon("https://legacy.example").starts_with("data:image/png;base64,"));}
 assert(vantage::safe_download_path(root,"../../passwd")==root/"passwd");assert(vantage::safe_download_path(root,".profile")==root/"download.profile");assert(vantage::safe_download_path(root,std::string("bad\0name",8))==root/"badname");
 {const auto path=vantage::safe_download_path(root,std::string(200,'a')+".png");assert(path.filename().string().size()==120);assert(path.extension()==".png");}
 {const auto completed=root/"completed.zip";std::ofstream file(completed);file<<"done";file.close();vantage::UserDataStore data(root/"reconcile.sqlite3");const auto done=data.add_download("https://example.com/done",completed.string(),"downloading",1);const auto missing=data.add_download("https://example.com/missing",(root/"missing").string(),"downloading",2);data.reconcile_downloads();const auto records=data.downloads();assert(records.size()==2);assert(records[0].id==missing&&records[0].status=="interrupted");assert(records[1].id==done&&records[1].status=="complete"&&records[1].received==4);}
 const auto private_path=root/"private.sqlite3";{vantage::UserDataStore data(private_path,true);data.add_bookmark({"https://private.invalid","Private"});assert(data.bookmarks().size()==1);data.add_history("https://private.invalid","Private",1);assert(data.history().empty());assert(data.add_download("https://private.invalid/file","/tmp/file","complete",1)==0);assert(data.downloads().empty());}assert(!std::filesystem::exists(private_path));std::filesystem::remove_all(root);
}
