#include "user_data.h"
#include <sqlite3.h>
#include <algorithm>
#include <cctype>
#include <stdexcept>
namespace {
void exec(sqlite3 *db, const char *sql) { char *error=nullptr; if (sqlite3_exec(db,sql,nullptr,nullptr,&error)!=SQLITE_OK) { std::string message=error?error:sqlite3_errmsg(db); sqlite3_free(error); throw std::runtime_error(message); } }
void migrate(sqlite3 *db,const char *sql){char*error=nullptr;if(sqlite3_exec(db,sql,nullptr,nullptr,&error)!=SQLITE_OK){const std::string message=error?error:"";sqlite3_free(error);if(message.find("duplicate column name")==std::string::npos)throw std::runtime_error(message);}}
void require(bool ok, sqlite3 *db) { if (!ok) throw std::runtime_error(sqlite3_errmsg(db)); }
}
namespace vantage {
UserDataStore::UserDataStore(const std::filesystem::path &path, bool private_mode) : private_mode_(private_mode) {
    const auto target=private_mode?std::string(":memory:"):path.string();
    if (!private_mode && path.has_parent_path()) std::filesystem::create_directories(path.parent_path());
    if (sqlite3_open_v2(target.c_str(),&database_,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE,nullptr)!=SQLITE_OK) throw std::runtime_error("open user data");
    exec(database_,"CREATE TABLE IF NOT EXISTS bookmarks(uri TEXT PRIMARY KEY,title TEXT NOT NULL);"
        "CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY,uri TEXT NOT NULL,title TEXT NOT NULL,visited_at INTEGER NOT NULL);"
        "CREATE INDEX IF NOT EXISTS history_visited_at ON history(visited_at DESC);"
        "CREATE TABLE IF NOT EXISTS downloads(id INTEGER PRIMARY KEY,uri TEXT NOT NULL,destination TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL,received INTEGER NOT NULL DEFAULT 0,total INTEGER NOT NULL DEFAULT 0);"
        "CREATE INDEX IF NOT EXISTS downloads_created_at ON downloads(created_at DESC);"
        "CREATE TABLE IF NOT EXISTS favicons(page_uri TEXT PRIMARY KEY,data_uri TEXT NOT NULL);"
        "CREATE TABLE IF NOT EXISTS permissions(origin TEXT NOT NULL,capability TEXT NOT NULL,decision INTEGER NOT NULL CHECK(decision BETWEEN 0 AND 2),PRIMARY KEY(origin,capability));");
    migrate(database_,"ALTER TABLE downloads ADD COLUMN received INTEGER NOT NULL DEFAULT 0");
    migrate(database_,"ALTER TABLE downloads ADD COLUMN total INTEGER NOT NULL DEFAULT 0");
}
UserDataStore::~UserDataStore(){if(database_)sqlite3_close(database_);}
void UserDataStore::add_bookmark(const Bookmark &bookmark){
    if(bookmark.uri.empty())throw std::invalid_argument("bookmark URI must not be empty");
    sqlite3_stmt *s=nullptr; require(sqlite3_prepare_v2(database_,"INSERT INTO bookmarks(uri,title) VALUES(?,?) ON CONFLICT(uri) DO UPDATE SET title=excluded.title",-1,&s,nullptr)==SQLITE_OK,database_); sqlite3_bind_text(s,1,bookmark.uri.c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(s,2,bookmark.title.c_str(),-1,SQLITE_TRANSIENT); require(sqlite3_step(s)==SQLITE_DONE,database_); sqlite3_finalize(s);
}
void UserDataStore::remove_bookmark(const std::string &uri){sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"DELETE FROM bookmarks WHERE uri=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,uri.c_str(),-1,SQLITE_TRANSIENT);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
void UserDataStore::update_bookmark(const std::string &old_uri,const Bookmark &bookmark){if(bookmark.uri.empty())throw std::invalid_argument("bookmark URI must not be empty");sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"DELETE FROM bookmarks WHERE uri=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,old_uri.c_str(),-1,SQLITE_TRANSIENT);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);add_bookmark(bookmark);}
std::vector<Bookmark> UserDataStore::bookmarks() const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT uri,title FROM bookmarks ORDER BY title,uri",-1,&s,nullptr)==SQLITE_OK,database_);std::vector<Bookmark> out;while(sqlite3_step(s)==SQLITE_ROW)out.push_back({reinterpret_cast<const char*>(sqlite3_column_text(s,0)),reinterpret_cast<const char*>(sqlite3_column_text(s,1))});sqlite3_finalize(s);return out;}
bool UserDataStore::is_bookmarked(const std::string &uri) const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT 1 FROM bookmarks WHERE uri=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,uri.c_str(),-1,SQLITE_TRANSIENT);const bool found=sqlite3_step(s)==SQLITE_ROW;sqlite3_finalize(s);return found;}
void UserDataStore::set_favicon(const std::string&page_uri,const std::string&data_uri){if(private_mode_||page_uri.empty()||data_uri.empty())return;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"INSERT INTO favicons(page_uri,data_uri) VALUES(?,?) ON CONFLICT(page_uri) DO UPDATE SET data_uri=excluded.data_uri",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,page_uri.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,data_uri.c_str(),-1,SQLITE_TRANSIENT);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
std::string UserDataStore::favicon(const std::string&page_uri) const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT data_uri FROM favicons WHERE page_uri=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,page_uri.c_str(),-1,SQLITE_TRANSIENT);std::string out;if(sqlite3_step(s)==SQLITE_ROW)out=reinterpret_cast<const char*>(sqlite3_column_text(s,0));sqlite3_finalize(s);constexpr std::string_view legacy="data:image/x-icon;base64,";if(out.starts_with(legacy)){const auto payload=out.substr(legacy.size());if(payload.starts_with("iVBOR"))out="data:image/png;base64,"+payload;else if(payload.starts_with("UklGR"))out="data:image/webp;base64,"+payload;else if(payload.starts_with("PD94bW")||payload.starts_with("PHN2Z"))out="data:image/svg+xml;base64,"+payload;}return out;}
void UserDataStore::add_history(const std::string &uri,const std::string &title,std::int64_t visited_at){if(private_mode_||uri.empty())return;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"INSERT INTO history(uri,title,visited_at) VALUES(?,?,?)",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,uri.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,title.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,3,visited_at);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
std::vector<HistoryEntry> UserDataStore::history(std::size_t limit) const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT id,uri,title,visited_at FROM history ORDER BY visited_at DESC,id DESC LIMIT ?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_int64(s,1,static_cast<sqlite3_int64>(limit));std::vector<HistoryEntry>out;while(sqlite3_step(s)==SQLITE_ROW)out.push_back({sqlite3_column_int64(s,0),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),sqlite3_column_int64(s,3)});sqlite3_finalize(s);return out;}
void UserDataStore::clear_history(){if(private_mode_)return;exec(database_,"DELETE FROM history;");}
void UserDataStore::remove_history(const std::vector<std::int64_t>&ids){if(private_mode_)return;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"DELETE FROM history WHERE id=?",-1,&s,nullptr)==SQLITE_OK,database_);for(const auto id:ids){sqlite3_bind_int64(s,1,id);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_reset(s);sqlite3_clear_bindings(s);}sqlite3_finalize(s);}
std::int64_t UserDataStore::add_download(const std::string &uri,const std::string &destination,const std::string &status,std::int64_t created_at){if(private_mode_)return 0;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"INSERT INTO downloads(uri,destination,status,created_at) VALUES(?,?,?,?)",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,uri.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,destination.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,status.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,4,created_at);require(sqlite3_step(s)==SQLITE_DONE,database_);const auto id=sqlite3_last_insert_rowid(database_);sqlite3_finalize(s);return id;}
void UserDataStore::update_download(std::int64_t id,const std::string &status){if(private_mode_||id==0)return;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"UPDATE downloads SET status=? WHERE id=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,status.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,2,id);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
void UserDataStore::update_download_progress(std::int64_t id,std::uint64_t received,std::uint64_t total){if(private_mode_||id==0)return;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"UPDATE downloads SET received=?,total=? WHERE id=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_int64(s,1,static_cast<sqlite3_int64>(received));sqlite3_bind_int64(s,2,static_cast<sqlite3_int64>(total));sqlite3_bind_int64(s,3,id);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
void UserDataStore::reconcile_downloads(){if(private_mode_)return;for(const auto&entry:downloads()){if(entry.status!="downloading")continue;std::error_code error;const auto exists=std::filesystem::is_regular_file(entry.destination,error);const auto size=exists?std::filesystem::file_size(entry.destination,error):0;const bool complete=exists&&!error&&size>0&&(entry.total==0||size>=entry.total);if(complete){update_download_progress(entry.id,size,entry.total?entry.total:size);update_download(entry.id,"complete");}else update_download(entry.id,"interrupted");}}
void UserDataStore::remove_download(std::int64_t id){if(private_mode_)return;sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"DELETE FROM downloads WHERE id=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_int64(s,1,id);require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
std::vector<DownloadEntry> UserDataStore::downloads(std::size_t limit) const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT id,uri,destination,status,created_at,received,total FROM downloads ORDER BY created_at DESC,id DESC LIMIT ?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_int64(s,1,static_cast<sqlite3_int64>(limit));std::vector<DownloadEntry>out;while(sqlite3_step(s)==SQLITE_ROW)out.push_back({sqlite3_column_int64(s,0),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),reinterpret_cast<const char*>(sqlite3_column_text(s,3)),sqlite3_column_int64(s,4),static_cast<std::uint64_t>(sqlite3_column_int64(s,5)),static_cast<std::uint64_t>(sqlite3_column_int64(s,6))});sqlite3_finalize(s);return out;}
void UserDataStore::set_permission(const std::string &origin,const std::string &capability,Permission value){if(!origin.starts_with("https://")&& !origin.starts_with("http://"))throw std::invalid_argument("permission origin must be HTTP(S)");sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"INSERT INTO permissions(origin,capability,decision) VALUES(?,?,?) ON CONFLICT(origin,capability) DO UPDATE SET decision=excluded.decision",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,origin.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,capability.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,3,static_cast<int>(value));require(sqlite3_step(s)==SQLITE_DONE,database_);sqlite3_finalize(s);}
Permission UserDataStore::permission(const std::string &origin,const std::string &capability) const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT decision FROM permissions WHERE origin=? AND capability=?",-1,&s,nullptr)==SQLITE_OK,database_);sqlite3_bind_text(s,1,origin.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,capability.c_str(),-1,SQLITE_TRANSIENT);const auto result=sqlite3_step(s);const auto value=result==SQLITE_ROW?static_cast<Permission>(sqlite3_column_int(s,0)):Permission::ask;sqlite3_finalize(s);return value;}
std::vector<PermissionEntry> UserDataStore::permissions() const {sqlite3_stmt*s=nullptr;require(sqlite3_prepare_v2(database_,"SELECT origin,capability,decision FROM permissions ORDER BY origin,capability",-1,&s,nullptr)==SQLITE_OK,database_);std::vector<PermissionEntry>out;while(sqlite3_step(s)==SQLITE_ROW)out.push_back({reinterpret_cast<const char*>(sqlite3_column_text(s,0)),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),static_cast<Permission>(sqlite3_column_int(s,2))});sqlite3_finalize(s);return out;}

std::filesystem::path safe_download_path(const std::filesystem::path &directory,const std::string &suggested){
    std::string name=std::filesystem::path(suggested).filename().string();
    name.erase(std::remove_if(name.begin(),name.end(),[](unsigned char c){return c<32||c==127||c=='/'||c=='\\';}),name.end());
    if(name.empty()||name=="."||name=="..")name="download";
    if(name.front()=='.')name="download"+name;
    constexpr std::size_t max_name_bytes=120;
    if(name.size()>max_name_bytes){const auto extension=std::filesystem::path(name).extension().string();const auto suffix=extension.size()<=12?extension:std::string{};name.resize(max_name_bytes-suffix.size());name+=suffix;}
    const auto candidate=(directory/name).lexically_normal();
    if(candidate.parent_path()!=directory.lexically_normal())throw std::runtime_error("download escaped destination");
    return candidate;
}
}
